apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - assisted-service-config.yaml
  - baremetal.yaml
  - hostedcluster.yaml
  - infra-env.yaml
  - namespaces.yaml
  - nodepool.yaml
  - prereqs.yaml
  - rbac.yaml
