---
apiVersion: v1
kind: Namespace
metadata:
  name: clusters-hosted-ipv4
spec: {}
status: {}
---
apiVersion: v1
kind: Namespace
metadata:
  name: clusters
spec: {}
status: {}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: capi-provider-role
  namespace: clusters-hosted-ipv4
rules:
- apiGroups:
  - agent-install.openshift.io
  resources:
  - agents
  verbs:
  - '*'
---
apiVersion: v1
data:
  .dockerconfigjson: 'eyJhdXRocyI6IHsiY2xvdWQub3BlbnNoaWZ0LmNvbSI6IHsiYXV0aCI6ICJiM0JsYm5Ob2FXWjBMWEpsYkdWaGMyVXRaR1YySzI5amJWOWhZMk5sYzNOZk5ERTFNVGt4TUdFMU1qSXhORGRpTkdJM01UUTNZamRqTURRNE0yRmpaV002V1VNNU5VSlVSa1JSUVVoSFVVY3hRVmxPUjFwWFNWTTFNa05GT0VORVdrVktTelpXVkZZNFJERlFWbEF6TmxwTlIwZzFTVkJVV2tSUE9FUXlXazlYTlE9PSIsICJlbWFpbCI6ICJyb2dlci56aW1tZXJtYW5uQGludmVudHguY2gifSwgInF1YXkuaW8iOiB7ImF1dGgiOiAiYjNCbGJuTm9hV1owTFhKbGJHVmhjMlV0WkdWMksyOWpiVjloWTJObGMzTmZOREUxTVRreE1HRTFNakl4TkRkaU5HSTNNVFEzWWpkak1EUTRNMkZqWldNNldVTTVOVUpVUmtSUlFVaEhVVWN4UVZsT1IxcFhTVk0xTWtORk9FTkVXa1ZLU3paV1ZGWTRSREZRVmxBek5scE5SMGcxU1ZCVVdrUlBPRVF5V2s5WE5RPT0iLCAiZW1haWwiOiAicm9nZXIuemltbWVybWFubkBpbnZlbnR4LmNoIn0sICJyZWdpc3RyeS5jb25uZWN0LnJlZGhhdC5jb20iOiB7ImF1dGgiOiAiZkhWb1l5MXdiMjlzTFRaa1lqUmhOVEUxTFdOaE5qTXROR0k0WlMxaU1XRXpMVFJtT0RkbE5qa3dZekZsTkRwbGVVcG9Za2RqYVU5cFNsTlZlbFY0VFdsS09TNWxlVXA2WkZkSmFVOXBTVEpOYlZKcldsUk9iRnBVU214UFZGRXdXa2RPYUZscWJHdE5SMDVwVGxSbk5WcFhWWGRQVjFVMVdsTktPUzVaU1cxT2RFZFdRa2hyUldjeVNUWnNaM2hoU3pCZlJWaFhhbWRLWW1kQllsbDNaWE5RT0hObE1sVlFWbm80TWpadlR6Y3pTbkJwTldRM00wWnRNVzFDTFZwSFdrOXNhbVZSVVRKZk4ySkJUMnRuYW5SMFJsUlZaV3BxVkcxNE1FUkhaRGhMVFZobFRVbzFlVzk2VmpNMlVIbDVSMkpqYmpsakxUVk1PR2xEYnpJMlp5MVNjVzlUWjFwaWJFaFpNak5QUkRsVE1XcDBjRmxQVmt0VVozaHNNVTlYYVZjelZGODJSVGhPVTJaMVdsWkhhVGx1Tkc1U1lsQXpUMk40WkZkc2NXTlNTbEp6Ukc5eGJVRXlkMVEzU1ZkRlJsOXRiRUZ3UkRaalVUSkxNVTkzVG5OTmFIbDJibkZ1TTFJM09VRlJSMGhXZVdSeFdqTmxNMUF4VW5CTlN6SkxkazlGTFUxT1UzQkNTSGhMWTNST1FYTnFlVEpRV1dKMmNsOWxYMjEyVG5KSFpYVnlUbUpRZGxaUWFucEpNMFJrUVRobVdVdFlTa2d6Vm1oNmVsOTRZV1F0WTE5WWJraDZUazFVU1RJeFFsa3dSV1ZYT0doWWQwRjRlbGhUV2s4ek1rcG5Ta1pYVUdaS05UQkphbDlMUkZCNlRsZHRjbUpDUzJ0RVpESk5VVWg2TVZKUlQxWk9TVjlIWTJ4VlMwOXFkRjl3WmsxU2VuZFhOM3BQTkdwblVHZzBNME5YY1RodE1qQlFhMlV6YTBGa2VVeEZhREp3ZGpWNmVXOHRjR0o2ZG14UUxUUnFPRVJvUkc5dk9XMHRWV3RCUlU5bmNtRlVNVWxDTmpsdmRXaHNXbFJrVEUwMlVEUjJjRkoxUkZsSlFYWnZSVU5NU1hwTlIwOVVOakF3V2xoWU5tTTVaM2htYXprdGVHRlpOV1Z2YTBab1FtbE9SVGROVFhScGJGUkVhRXBZVWkxUlYzQmZNVGc0UVc5cE5XTlFVVVpwVUhSc2VEaE9abkZYTFd0WFdtVXlNMGxKYURRMFNIZEJiRWhhZW1GTE1rWkpWbTk2UmtOU1pWTmZXblY1Vm5KRVMyRjNVVWh5ZDFWblpuVnBSbXg0U1UxTlkwUnBVM1ZIVlU4eVpHZGtOVkJ0UjBOdk5GTmlhMXBSTkhCa2IwUmhSblpLYW5SUVlrZFlWMVJJVlhwdUxVVTVSUT09IiwgImVtYWlsIjogInJvZ2VyLnppbW1lcm1hbm5AaW52ZW50eC5jaCJ9LCAicmVnaXN0cnkucmVkaGF0LmlvIjogeyJhdXRoIjogImZIVm9ZeTF3YjI5c0xUWmtZalJoTlRFMUxXTmhOak10TkdJNFpTMWlNV0V6TFRSbU9EZGxOamt3WXpGbE5EcGxlVXBvWWtkamFVOXBTbE5WZWxWNFRXbEtPUzVsZVVwNlpGZEphVTlwU1RKTmJWSnJXbFJPYkZwVVNteFBWRkV3V2tkT2FGbHFiR3ROUjA1cFRsUm5OVnBYVlhkUFYxVTFXbE5LT1M1WlNXMU9kRWRXUWtoclJXY3lTVFpzWjNoaFN6QmZSVmhYYW1kS1ltZEJZbGwzWlhOUU9ITmxNbFZRVm5vNE1qWnZUemN6U25CcE5XUTNNMFp0TVcxQ0xWcEhXazlzYW1WUlVUSmZOMkpCVDJ0bmFuUjBSbFJWWldwcVZHMTRNRVJIWkRoTFRWaGxUVW8xZVc5NlZqTTJVSGw1UjJKamJqbGpMVFZNT0dsRGJ6STJaeTFTY1c5VFoxcGliRWhaTWpOUFJEbFRNV3AwY0ZsUFZrdFVaM2hzTVU5WGFWY3pWRjgyUlRoT1UyWjFXbFpIYVRsdU5HNVNZbEF6VDJONFpGZHNjV05TU2xKelJHOXhiVUV5ZDFRM1NWZEZSbDl0YkVGd1JEWmpVVEpMTVU5M1RuTk5hSGwyYm5GdU0xSTNPVUZSUjBoV2VXUnhXak5sTTFBeFVuQk5TekpMZGs5RkxVMU9VM0JDU0hoTFkzUk9RWE5xZVRKUVdXSjJjbDlsWDIxMlRuSkhaWFZ5VG1KUWRsWlFhbnBKTTBSa1FUaG1XVXRZU2tnelZtaDZlbDk0WVdRdFkxOVlia2g2VGsxVVNUSXhRbGt3UldWWE9HaFlkMEY0ZWxoVFdrOHpNa3BuU2taWFVHWktOVEJKYWw5TFJGQjZUbGR0Y21KQ1MydEVaREpOVVVoNk1WSlJUMVpPU1Y5SFkyeFZTMDlxZEY5d1prMVNlbmRYTjNwUE5HcG5VR2cwTTBOWGNUaHRNakJRYTJVemEwRmtlVXhGYURKd2RqVjZlVzh0Y0dKNmRteFFMVFJxT0VSb1JHOXZPVzB0Vld0QlJVOW5jbUZVTVVsQ05qbHZkV2hzV2xSa1RFMDJVRFIyY0ZKMVJGbEpRWFp2UlVOTVNYcE5SMDlVTmpBd1dsaFlObU01WjNobWF6a3RlR0ZaTldWdmEwWm9RbWxPUlRkTlRYUnBiRlJFYUVwWVVpMVJWM0JmTVRnNFFXOXBOV05RVVVacFVIUnNlRGhPWm5GWExXdFhXbVV5TTBsSmFEUTBTSGRCYkVoYWVtRkxNa1pKVm05NlJrTlNaVk5mV25WNVZuSkVTMkYzVVVoeWQxVm5ablZwUm14NFNVMU5ZMFJwVTNWSFZVOHlaR2RrTlZCdFIwTnZORk5pYTFwUk5IQmtiMFJoUm5aS2FuUlFZa2RZVjFSSVZYcHVMVVU1UlE9PSIsICJlbWFpbCI6ICJyb2dlci56aW1tZXJtYW5uQGludmVudHguY2gifSwgImhhcmJvci5vY3Bsb2NhbC5pdGl4IjogeyJhdXRoIjogIllXUnRhVzQ2VXpCdGJUTnlNRGtoIiwgImVtYWlsIjogImpoZW5kcml4QGthcm1hbGFicy5jb3JwIn19fQ=='
kind: Secret
metadata:
  name: hosted-ipv4-pull-secret
  namespace: clusters
---
apiVersion: v1
kind: Secret
metadata:
  name: sshkey-cluster-hosted-ipv4
  namespace: clusters
stringData:
  id_rsa.pub: 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINrLu1SjuRfuH22x6DgrVfBcr/GKoT1ORjICwsm5Dz7T roger.zimmermann@inventx.ch'
---
apiVersion: v1
data:
  key: nTPtVBEt03owkrKhIdmSW8jrWRxU57KO/fnZa8oaG0Y=
kind: Secret
metadata:
  name: hosted-ipv4-etcd-encryption-key
  namespace: clusters
type: Opaque
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-ca-bundle
  namespace: clusters
data:
  ca-bundle.crt: |
    -----BEGIN CERTIFICATE-----
    MIIFwzCCA6ugAwIBAgIUGhj79nFrgrhugD1Xo5XAWzxTKrgwDQYJKoZIhvcNAQEN
    BQAwcTELMAkGA1UEBhMCQ04xDjAMBgNVBAgMBURhdm9zMQ4wDAYDVQQHDAVEYXZv
    czEQMA4GA1UECgwHZXhhbXBsZTERMA8GA1UECwwIUGVyc29uYWwxHTAbBgNVBAMM
    FGhhcmJvci5vY3Bsb2NhbC5pdGl4MB4XDTI1MTEwNzE1NDkyNloXDTM1MTEwNTE1
    NDkyNlowcTELMAkGA1UEBhMCQ04xDjAMBgNVBAgMBURhdm9zMQ4wDAYDVQQHDAVE
    YXZvczEQMA4GA1UECgwHZXhhbXBsZTERMA8GA1UECwwIUGVyc29uYWwxHTAbBgNV
    BAMMFGhhcmJvci5vY3Bsb2NhbC5pdGl4MIICIjANBgkqhkiG9w0BAQEFAAOCAg8A
    MIICCgKCAgEAvJPPWd7ng5qdIc4/yKLFqL+3Fi7a0ni/A1/ZvPB5tLUklg81/1xZ
    Bm+YlBhOxDLLRvnsHQNgG5xhU2nPN3tjJgA6glHpR8/Bmvleb3LBM8X1fhVEMl70
    Dm44emLmWFyRdaiI7mL36D6g7G672Cb+uMikFgUd78bz9JrbgXWp3ipioKgOuLpO
    t3q19F27WcqxE/Hrm0+sDP7ckDnGcxOTt/ZuUy1BXRfVi1P/SNsGDGd3J38MuWoV
    1viu4n1aFzoRqV6afGWbcqTnMaIz4//rVYuPRu0/Bhywhsa2EiMh5ZH7AFlFNJcx
    7BoGfHQM2jb8R3QBtkj7VZAZCThxxvFWlo3tMh/GIz3xbCR6J+pJ0PaGBAN8qaVz
    JQ2CZR4YeuJ2PkottxEzsWQoCpKYKUVDCUneHYOjgMFcH1yvfLmJlMtW0VE91ovh
    GRh6QGQCrsG0q6bK79DMqkEn23LO5r0zCJctGFtuWr1SgVczTW+ctwpLvEW2CS9g
    M+SagHDLoKcrQyIV/aACjMpDAKCcHK8UQw0MtsZQEOKZwnJll023MwPBwDXh2MP6
    0+J9cbf2uBQXpZQdq2o4GTzAKZaEEKXG1KFZlF6ISPB6JiZZAXpcco5aQYy6fUOj
    7miLLviUKXW+Xxp84tAZVxbEJ+UJ250I9qvFd5Ku+kCsiwJC/3XWSrcCAwEAAaNT
    MFEwHQYDVR0OBBYEFHuBPG/j/nIqEg1kg7fjkAxw+s1wMB8GA1UdIwQYMBaAFHuB
    PG/j/nIqEg1kg7fjkAxw+s1wMA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZIhvcNAQEN
    BQADggIBADBjNF7u4VXdB2uIadl7vH47JuOzTGt4VcRc2j3i1ykR7WO2d2qWdNOu
    0UQGgb/K1NkyxJNTRbflV7JU25ouhb7JMJE+RO6/144AgGV+AZcDv83y6viyUbZn
    zk/1K1x3ivd6UMnYcnSQMFE8IRMoECqNmxDrnOMOQagqBdzQGIqWPru7cxsXLtXY
    UCnpSA2+ZAGP5/aBlcuqiqWVWKV8xecuXucMwUcTdnvQfgk+Rq74/2Rh/n77+qLx
    mKcHApk4fAxPBQGeV5cYMVcq7iKEt0mWB22gpcYZkWSoBJTaSbIeMbMHI7iZPNLe
    bGI1VlClXP+5vt6X7TaSQHF3IWsYO27gJRfVa/HCHnaRh4gAonVAHSHm9C/jYJIA
    bN4gAEkvOH2q8I6IC9M8QuNaQXUCwyBnaW5gw39fMPYi42SuzME8WnXZ8kNNGYQ0
    2ilZj6TNoJDYCbkZPjLdKQd+MIzcvK1js2XEDyYJfNdRvxG4n7/ceb4lWSb+Ia1b
    1nWdqhLkIETrxg4KiySkRJ2MXMdgMW9fhQBm9cBBJ/3M+HSVoODbVm++5/WOWBWp
    S2PkxDJyOcOdCoRndx7ULsix1jd0ifd125s9Tv4zhASSTK3SRoVXcXMgULZj7V+C
    uSM33FKKiMc1Slu422WLrrST1Xfav1Jx9UoFeJo4UvfE0iQiHFzI
    -----END CERTIFICATE-----